# My First README.md
## **Delaney Cummins**
1. This is fun so far.
2. Starting to grasp the baby steps.
3. But still unable to help any one in the class chat with my limited knowledge!


* *Hope this readme is correct*
* Does this pass as an unordered list?
* I think so!

>Block quotes look fancy! I'm going to ramble here to check out that sick wrap around. Awwww yeah


***
*Is this text too far from the horizontal line or is it just me?*

[One of my favorite comic book artists] (http://reyyy.com/)

[screenshot of my directory](.images/screenshot-1.ong
)
